version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "8082:80"  # Change to another port, e.g., 8082

  backend:
    build: ./backend
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sample_app
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
